### ISSUE TITLE
Broken Installation

### ISSUE THREAD

**Issue by realsama** [ElasticEmail/elasticemail-python#1]
I can't currently install this package due to this library missing recently added requirements inside the install_requires config in the setup.py file. Thanks!

Edit

Apparently, the recent updates include a breaking change that gives the below error. The library can't be used currently. 

```
File "/usr/local/lib/python3.10/site-packages/ElasticEmail/api/emails_api.py", line 15, in <module>
    from ElasticEmail.api_client import ApiClient, Endpoint as _Endpoint
ImportError: cannot import name 'Endpoint' from 'ElasticEmail.api_client' (/usr/local/lib/python3.10/site-packages/ElasticEmail/api_client.py)
```

**Comment by ElasticEmail** [comment]
Hi,
We didn't saw that OpenAPI Generator made breaking change to Python generator and released breaking change in our library. Now we have switched to python-prior generator to not make such a breaking change without prior notification.
