### ISSUE TITLE
 cannot import name 'Endpoint' from 'ElasticEmail.api_client

### ISSUE THREAD

**Issue by webcode2** [ElasticEmail/elasticemail-python#4]
`
 from ElasticEmail.api import emails_api
  File "C:\Users\EASY\production\python\wallace\wallacebend\.venv\lib\site-packages\ElasticEmail\api\emails_api.py", line 15, in <module>
    from ElasticEmail.api_client import ApiClient, Endpoint as _Endpoint
ImportError: cannot import name 'Endpoint' from 'ElasticEmail.api_client' (C:\Users\EASY\production\python\wallace\wallacebend\.venv\lib\site-packages\ElasticEmail\api_client.py)
`

**Comment by crlosif** [comment]
I got same error

**Comment by crlosif** [comment]
@webcode2 
ElasticEmail Package's version was upgraded from 4.0.23 to 4.0.24 at Nov, 27th so 4.0.24 is not working correctly now
 
I tried with `pip install ElasticEmail==4.0.23` and it works now

**Comment by webcode2** [comment]
> @webcode2 ElasticEmail Package's version was upgraded from 4.0.23 to 4.0.24 at Nov, 27th so 4.0.24 is not working correctly now
> 
> I tried with `pip install ElasticEmail==4.0.23` and it works now

Thanks for the heads Up

**Comment by webcode2** [comment]
Thanks @kitty-0315  for the heads up

**Comment by radzawee** [comment]
We have released updated library built with OpenAPI Generator 7.5, it's not compatible with older builds. New version is 4.10, available on PyPI too.
